---
- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_os_family == "Ubuntu"

- include_tasks: caldera.yml

- include_tasks: daemonize.yml
