---
- name: install systemd configuration
  become: yes
  ansible.builtin.template:
    src: systemd-caldera-agent.service.j2
    dest: /lib/systemd/system/caldera-agent.service
    mode: '0644'
    backup: yes
  register: systemd
  
- name: reload systemd
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes
    name: caldera-agent
  when: systemd.changed
  ignore_errors: true

- name: enable and start caldera-agent systemd service
  become: yes
  ansible.builtin.systemd:
    name: caldera-agent
    enabled: yes
    state: 'started'

#- name: Restart Caldera agent sevice
#  become: yes
#  ansible.builtin.systemd:
#    state: 'restarted'
#    name: caldera-agent
