---
- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_os_family == "Debian"

- include_tasks: agent.yml

- include_tasks: daemonize.yml
