name: AWS deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: false
        type: string
      environment:
        description: 'Environment to run tests against'
        type: enviroment
        required: false

jobs:
  print-tag:
    runs-on: ubuntu-latest
#    if:  ${{ inputs.print_tags }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Listar los ficheros
        run: ls -lart
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
      - name: Verify Terraform version
        run: terraform --version
