name: AWS deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: false
        type: string
      environment:
        description: 'Environment to run tests against'
        type: enviroment
        required: false

jobs:
  Deploy-caldera-server:
    runs-on: ubuntu-latest
#    if:  ${{ inputs.print_tags }}
    steps:
      - name: Set vars
        run: |
          export TF_WORKSPACE=$GITHUB_WORKSPACE/AWS_infra
          echo $TF_WORKSPACE
          ls -laRt $PWD
      - name: Check out code
        uses: actions/checkout@v2
      - name: tesy
        run: pwd
      - name: Listar los ficheros
        run: ls -d $PWD/*
      - name: enviroment vars
        run: env
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
      - name: Verify Terraform version
        run: terraform --version
      - name: Terraform init
        env:
          TF_WORKSPACE: $GITHUB_WORKSPACE/AWS_infra
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo $TF_WORKSPACE
          echo $AWS_ACCESS_KEY_ID
          cd $GITHUB_WORKSPACE/AWS_infra && terraform init -input=false
      - name: Terraform validation
        run: terraform validate
#      - name: Terraform plan
#        run: terraform plan  -no-color -target=aws_instance.caldera_server -detailed-exitcode
      - name: Listar los ficheros
        if: ${{ always() }}
        run: ls -lart $TF_WORKSPACE

