name: Testing
on:
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Cloud to deploy against'
        type: choice
        required: true
        default: "AWS"
        options:
        - AWS
        - Azure
      account:
        description: 'Account where deploy'
        type: choice
        required: true
        default: "ASM"
        options:
        - ASM
        - ACD

jobs:
  deploy-caldera-server:
    runs-on: ubuntu-20.04
    env:
#      ID: ${{ inputs.cloud }}_ACCESS_KEY_ID
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_ACCESS_KEY_ID: ${{ secrets[env.ID] }}
#      AWS_ACCESS_KEY_ID: format('{{ {0}_{1}_ID }}', ${{ inputs.cloud }}, ${{ inputs.account }})
      AWS_ACCESS_KEY_ID: ${{ format('{0}_ {1}_{2}', 'Mona', 'the', 'Octocat') }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
#    - name: Install AZ cli
#      run: |
#       # curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
#        az version
#    - name: 'Az CLI login'
#      uses: azure/login@ec3c14589bd3e9312b3cc8c41e6860e258df9010
#      with:
#          client-id: ${{ secrets.AZURE_CLIENT_ID }}
#          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#
#    - name: 'Run Azure CLI commands'
#      run: |
#          az account show
#          az group list
#          pwd
#    - name: Check out the code
#      uses: actions/checkout@v3
    - name: test
      run: |
        echo Acces key $AWS_ACCESS_KEY_ID
#        echo "::set-env name=AS_ACCESS_KEY_ID::${{ secrets[env.AWS_ACCESS_KEY_ID] }}"
#        echo la key de aws $AWS_ACCESS_KEY_ID
#        echo la as $AS_ACCESS_KEY_ID
