name: Testing
on:
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Cloud to deploy against'
        type: choice
        required: true
        default: "AWS"
        options:
        - AWS
        - Azure
      account:
        description: 'Account where deploy'
        type: choice
        required: true
        default: "ASM"
        options:
        - ASM
        - ACD

jobs:
  deploy-caldera-server:
    runs-on: ubuntu-20.04
    env:
#      AWS_ACCESS_KEY_ID: ${{ inputs.cloud }}_ACCESS_KEY_ID
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets[inputs.cloud] }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: test
      run: |
        echo Acces key $AWS_ACCESS_KEY_ID
#        echo "::set-env name=AS_ACCESS_KEY_ID::${{ secrets[env.AWS_ACCESS_KEY_ID] }}"
#        echo la key de aws $AWS_ACCESS_KEY_ID
#        echo la as $AS_ACCESS_KEY_ID
