name: Testing
on:
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Cloud to deploy against'
        type: choice
        required: true
        default: "AWS"
        options:
        - AWS
        - Azure
      account:
        description: 'Account where deploy'
        type: choice
        required: true
        default: "ASM"
        options:
        - ASM
        - ACD

jobs:
  deploy-caldera-server:
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: test
      run: |
        echo Acces key
        echo $AWS_ACCESS_KEY_ID
        export ID=${{ inputs.cloud }}_ACCESS_KEY_ID
        export DEPLOY_ID=${{ secrets.`echo $ID` }}
        echo la key de aws $DEPLOY_ID
        echo El ID es $ID
        echo variable cloud ${{ inputs.cloud }}
